import Head from "next/head";
import axios from "axios";
import { publicRuntimeConfig } from "next.config";
import { PostResponseData } from "../types/blog";
import PostTile from "components/PostTile";
import styled from "styled-components";

type HomeType = {
  posts: PostResponseData;
};

export default function Home(props: HomeType) {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledPosts>
        <StyledTitle>The newest posts</StyledTitle>
        {props.posts.data.map((post) => (
          <PostTile {...post.attributes} key={post.id} />
        ))}
      </StyledPosts>
    </>
  );
}

export async function getStaticProps() {
  const allPosts = await axios(
    `${publicRuntimeConfig!.NEXT_PUBLIC_API_URL}/api/posts`
  );

  const newestPostsFrom = allPosts.data.meta.pagination.total - 6;

  const response = await axios(
    `${
      publicRuntimeConfig!.NEXT_PUBLIC_API_URL
    }/api/posts?pagination[start]=${newestPostsFrom}`
  );

  const data: PostResponseData = response.data;

  return {
    props: {
      posts: data,
    },
  };
}

const StyledTitle = styled.h2`
  font-size: 2.5rem;
  margin-left: 5px;
`;

const StyledPosts = styled.div`
  display: flex;
  flex-direction: column;
  height: auto;
  margin-top: 100px;
`;
